neuralinternet/SN27

- neurons/validator.py
this would fix the issue that validators hang after setting weights
> chore: changed wait_for_inclusion to False

- compute/__init__.py
- compute/protocol.py
- compute/utils.py
- neurons/miner.py
- neurons/register.py
- neurons/validator.py
added auto update feature for validators and miners
> Auto update Feature

- neurons/register.py
> Update register.py - added two arguments

- compute/__init__.py
- neurons/Validator/calculate_score.py
Please read carefully.
Also regarding my benchmark results, I revised a little bit the cpu & ram weight.
> hotfix: add limits to the current scoring system

- neurons/validator.py
Per attached image, blacklisting the top 4 hotkeys of the miner in the image
> add another blacklisted miner

- neurons/register_api.py
based on CLI version and add API part
> feat(register_api.py): add new API feature

- compute/__init__.py
- neurons/Miner/pow.py
- neurons/Validator/calculate_pow_score.py
- neurons/Validator/calculate_score.py
- neurons/Validator/pow.py
- neurons/miner.py
- neurons/validator.py
- requirements.txt
Reverts neuralinternet/compute-subnet#157 due to OOM issue, will merge new PR once fixed
> Revert "Update 1.4.3"

- neurons/miner.py
- requirements.txt
1. Change the allocation checking after WanDB init.
2. remove the websokcet package.
> fix: Change the allocation checking after WanDB init and remove the websokcet package.

- neurons/miner.py
check the file exist before open the file
> fix(miner.py): fix the allocation file is not exist

- neurons/miner.py
- neurons/register_api.py
- requirements.txt
- test-scripts/benchmark.py
1. fix the allocation file checking in the miner
2. update to the latest API
3. update the requirement for requests.
4. update the benchmark tool (PR#151)
> Dev api new

- cert/gen_ca.sh
- compute/protocol.py
- neurons/Miner/container.py
- neurons/miner.py
- neurons/register_api.py
1. update the certificate tool.
2. support docker restart function.
3. support change SSH key function.
> Change the certificate tool and support docker restart and change SSH key on API

- .env.example
- neurons/register_api.py
1. add the deallocation retry.
2. add the load notify URL from .env file
> fix(register_api.py): add deallocation retry and change the notify URL

- neurons/Miner/specs.py
- neurons/miner.py
comment out the unused spec query function
> fix(miner.py and specs.py): comment out unused spec function

- compute/__init__.py
- compute/utils/parser.py
- neurons/Validator/calculate_pow_score.py
- neurons/miner.py
- neurons/validator.py
Revert below two commits on upgrade the version to v1.4.7
commit: 02cd012a298a7de4225f9fc758250beb9628b292 
- feat: improved scoring of allocated miners
commit: 8608442df4964de1fd4eeea632b4f13947915fec 
- mod: whitelist and updated threshold
> v1.4.7 to revert scoring of allocated miners and whitelist/threshold update

- compute/__init__.py
- compute/utils/db.py
- compute/wandb/wandb.py
- neurons/Validator/calculate_pow_score.py
- neurons/Validator/database/allocate.py
- neurons/miner.py
- neurons/register.py
- neurons/validator.py
- requirements.txt
- option to penalize non-confirming miners via vali CLI trough scoring
- removed blacklist for valis that are not up-to-date
- bumped version to 1.4.8
> feat: option to penalize non-conforming miners

- compute/__init__.py
- requirements.txt
- Upgraded bittensor from 6.9.3 to 6.9.4 in requirements.txt
- bump version to 1.4.8
> Upgrade bittensor to 6.9.4

- compute/utils/socket.py
- compute/wandb/wandb.py
- neurons/miner.py
- neurons/register_api.py
- add /list/resources_wandb endpoint
- add miner port checker
- add miner dual allocation protection
> add resources_wandb endpoint and allocation protection.

- neurons/Miner/container.py
- neurons/miner.py
- neurons/register_api.py
This commit adds the `pause_container()` and `unpause_container()` functions to the `container.py` file in the `Miner` module. These functions allow pausing and unpausing of Docker containers. This feature enhances the flexibility and control of the container management system.
> feat: add pause and unpause container functionality

- neurons/register_api.py
- update the NOTIFY_RETRY_PERIOD to be 15 sec between each retry
- update ALLOCATE_CHECK_COUNT to check 120 times ( 120 * 15  = ~ 30 minutnes )
> Validator-settings-update

- compute/__init__.py
- compute/wandb/wandb.py
- neurons/Miner/http_server.py
- neurons/Validator/script.py
- neurons/miner.py
- neurons/register_api.py
- neurons/validator.py
- requirements.txt
- Miner port check & validator port scan feature
- Docker container creation possibility
- Automatic ssh login to mock docker containers to ensure access
- /list/resources_wandb ram size change from available ram to total ram
- /list/resources_wandb eliminate penalized_hotkeys listed miners
- /list/resources_wandb eliminate allocate_status = reserved
> Reporting service implementation and /list/resources_wandb adjustments

- neurons/register_api.py
the PR adds 2 new endpoints. 
- **/list/count_all_gpus/**: to count all the GPUs in the network. 
- **/list/count_all_gpus_by_mod**: same as above but gives the option to count by name, CPU, or Ram size.
> Czn 260 endpoint for showing counts

- neurons/Miner/container.py
- neurons/miner.py
- Update the container.py to compare public key to local saved allocation key for security.
- Update the miner.py based on the change of container.py.
> feat: security ssh keys.

- compute/__init__.py
- config.yaml
Reduce the score of low tier GPUs by 50%.
> perf: reduce score for low tier GPUs

- neurons/Miner/container.py
Not entirely sure which base branch to target, this can be deployed and should be trivial to rebase.
> fix(CSN-556): Rearrange docker image build

- README.md
🚀 [Feature]: Add Documentation for Finney Rate Limit Issue and Solution Options
Summary
This PR documents the current state of the Finney rate limit issue and proposes potential solutions to mitigate traffic reliance on our own subtensor. It introduces the need for a permanent solution while detailing the temporary workaround in the README.
Changes Made
🛠 Updated the README to include details on the Finney rate limit issue and the potential long-term solution.
Impact & Risks
⚠️ No breaking changes are introduced. However, the solution may require further optimization based on future developments with the Finney rate limit.
🔄 This update does not directly impact any existing functionality but aims to provide better clarity to the team and validators.
Testing & Validation
✅ Manual Testing: …
> Update README to clarify validator usage on local Subtensor instance

- compute/axon.py
1 - overwrite serve_extrinsic to use _version_as_int instead of bittensor version
2 - refactor Axon class to follow the latest bittensor update coding style.
3 - refactor the imports section
4 - remove prometheus
> fix(CD-1767): Miner version issue

- neurons/validator.py
1. remove the version limit to 600  to become queryable.
2. remove the miner staking limit to 1000 to become queryable.
> fix(validator.py): change the validator version and miner staking limit

- neurons/validator.py
adding the flag testing = True to the validator checker
> fix(csn-582) POG fix on the vali

- compute/__init__.py
- config.yaml
…models
Scores removed for all GPUs, except:
- NVIDIA H200
- NVIDIA H100 80GB HBM3
- NVIDIA H100 PCIe
- NVIDIA A100-SXM4-80GB
> feat(config.yaml): remove scores for all GPUs except select high-end

- neurons/Miner/container.py
- neurons/register_api.py
- The restart_container function restarts running, stopped, killed docker container.
- If the ssh container is not exist, register api returns error.
- https://neuralinternet.atlassian.net/jira/software/projects/CSN/boards/15?selectedIssue=CSN-232
> CSN-232: Fix issue in restart docker api

- .env.example
- compute/utils/db.py
Change the SQLite DB file path with an environment variable to call the ComputeDB function by the external register_api
> fix(CSN-361,db.py): change SQLite DB path with environment variable

- scripts/installation_script/README.md
- scripts/installation_script/compute_subnet_installer.sh
https://neuralinternet.atlassian.net/browse/CSN-798
> feat(CSN-798): check existing wandb api key during installation

- neurons/Miner/container.py
Resolved an issue where a container wasn't properly deallocated during POG
> Fix(csn-852): error killing container

- scripts/installation_script/README.md
- scripts/installation_script/compute_subnet_installer.sh
Solve problem with .env database, bittensor version, PM2 errors, subnet logo on first start.
> fix(CSN-863): fix critical installation script errors

- scripts/validate_miner_ports.py
- Replace bare except blocks with specific Exception handlers
- Add logging import and warning messages for IP service failures
- Allow KeyboardInterrupt and SystemExit to propagate correctly
- Fixes CodeQL security warnings in GitHub checks
> fix: improve exception handling in port validation script
